import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Global header */}
        {/* eslint-disable-next-line @next/next/no-head-element */}
        <div className="min-h-screen grid grid-rows-[auto_1fr]">
          {/* Header */}
          {/* @ts-expect-error Server Component default */}
          {require("@/src/components/Header").default()}
          {/* Main content */}
          <main className="mx-auto w-full max-w-6xl px-4 sm:px-6 py-6 sm:py-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
